name: artlab_service
description: "ArtLab Windows Service"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  encrypt_shared_preferences: ^0.8.0
  flutter_esc_pos_utils: ^1.0.1
  get: ^4.6.6
  qr_flutter: ^4.1.0
  windows_usb_printer: ^0.0.2+4
  dio: ^5.7.0
  charset_converter: ^2.3.0
  http: ^1.2.2
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true